/**
 * A single priced material line, generated by one of the AI-kalkylatorer
 * (wall-catalog.ts, floor-catalog.ts, …). This is the same shape the old
 * consumer cart engine's CatalogItem used — kept identical on purpose so
 * every existing calculator (all pure math, already tested) keeps working
 * unchanged — just without a retail store/domain to check out from.
 * `keywords`/`domain` stay for now as the calculators' own self-lookup
 * (see matchesMaterialItem below); nothing outside lib/cart-engine/*-catalog.ts
 * should need them.
 */
export type MaterialItem = {
  id: string;
  keywords: string[];
  displayName: string;
  unitLabel: string;
  basePriceSEK: number;
  naiveBrand: string;
  smartBrand: string;
  domain?: string;
  /** The quantity `unitPriceSEK` is multiplied by to get `basePriceSEK`
   *  (e.g. sheet count, m², liters — whatever varies with the project's
   *  dimensions). Lets a materialbank price genuinely override the
   *  per-unit price without needing to know the project's own math. */
  qty: number;
  /** The catalog's built-in per-unit price — always `basePriceSEK / qty`.
   *  Kept separate from `basePriceSEK` (rather than derived) so a
   *  materialbank match can replace just this and recompute the total. */
  unitPriceSEK: number;
  /** Set when a MaterialBankItem's own price replaced the simulated
   *  unitPriceSEK — lets the UI show "från din materialbank". */
  sourcedFromBank?: boolean;
};

/** Finds the material a raw id/string resolves to — used by each
 *  calculator's own test suite to catch keyword collisions. */
export function matchMaterialItem(raw: string, materials: MaterialItem[]): MaterialItem | null {
  const needle = raw.trim().toLowerCase();
  if (!needle) return null;
  return materials.find((item) => item.keywords.some((k) => needle.includes(k))) ?? null;
}
