/**
 * A single priced material line, generated by one of the AI-kalkylatorer
 * (wall-catalog.ts, floor-catalog.ts, …). This is the same shape the old
 * consumer cart engine's CatalogItem used — kept identical on purpose so
 * every existing calculator (all pure math, already tested) keeps working
 * unchanged — just without a retail store/domain to check out from.
 * `keywords`/`domain` stay for now as the calculators' own self-lookup
 * (see matchesMaterialItem below); nothing outside lib/cart-engine/*-catalog.ts
 * should need them.
 */
export type MaterialItem = {
  id: string;
  keywords: string[];
  displayName: string;
  unitLabel: string;
  basePriceSEK: number;
  naiveBrand: string;
  smartBrand: string;
  domain?: string;
};

/** Finds the material a raw id/string resolves to — used by each
 *  calculator's own test suite to catch keyword collisions. */
export function matchMaterialItem(raw: string, materials: MaterialItem[]): MaterialItem | null {
  const needle = raw.trim().toLowerCase();
  if (!needle) return null;
  return materials.find((item) => item.keywords.some((k) => needle.includes(k))) ?? null;
}
